import amqp_aio

PROTOCOL_HEADER = b"AMQP\x00"
VERSION = (0, 9, 1)
FRAME_END = b"\xce"

METHOD_TYPE = 1
HEADER_TYPE = 2
BODY_TYPE = 3
HEARTBEAT_TYPE = 8

FRAME_MIN_SIZE = 4096

# Information

PRODUCT = 'AMQP AIO Client Library'
LIB_VERSION = amqp_aio.__version__

# Connection Class Consts

CONNECTION_CLASS_ID = 10
CONNECTION_START_ID = 10
CONNECTION_START_OK_ID = 11
CONNECTION_SECURE_ID = 20
CONNECTION_SECURE_OK_ID = 21
CONNECTION_TUNE_ID = 30
CONNECTION_TUNE_OK_ID = 31
CONNECTION_OPEN_ID = 40
CONNECTION_OPEN_OK_ID = 41
CONNECTION_CLOSE_ID = 50
CONNECTION_CLOSE_OK_ID = 51

# Channel Class Consts

CHANNEL_CLASS_ID = 20
CHANNEL_OPEN_ID = 10
CHANNEL_OPEN_OK_ID = 11
CHANNEL_FLOW_ID = 20
CHANNEL_FLOW_OK_ID = 21
CHANNEL_CLOSE_ID = 40
CHANNEL_CLOSE_OK_ID = 41

# Exchange Class Consts

EXCHANGE_CLASS_ID = 40
EXCHANGE_DECLARE_ID = 10
EXCHANGE_DECLARE_OK_ID = 11
EXCHANGE_DELETE_ID = 20
EXCHANGE_DELETE_OK_ID = 21


# Queue Class Consts

QUEUE_CLASS_ID = 50
QUEUE_DECLARE_ID = 10
QUEUE_DECLARE_OK_ID = 11
QUEUE_BIND_ID = 20
QUEUE_BIND_OK_ID = 21
QUEUE_UNBIND_ID = 50
QUEUE_UNBIND_OK_ID = 51
QUEUE_PURGE_ID = 30
QUEUE_PURGE_OK_ID = 31
QUEUE_DELETE_ID = 40
QUEUE_DELETE_OK_ID = 41


